---
deployment:
  tasks:
    - export REPOPATH=/home/rudenuat/repositories/rudenua.tech/build/*
    - export SITEPATH=/home/yourdoma/public_html/
    - /bin/rsync -rav --exclude '.git' --exclude '.cpanel.yml' --del $REPOPATH $SITEPATH
